redis:
  host: 192.168.80.130
  port: 6379
  pool:
    max-active: 200
    max-wait: 1
    max-idle: 10
    min-idle: 0
  timeout: 1000


server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.80.131:3306/poem_analysis?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://192.168.80.131:3306/poem_analysis?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 10
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      filter:
        stat:
          enabled: true
        wall:
          enabled: false
          drop-table-allow: false

  rabbitmq:
    host: 192.168.80.131
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    # p端收到回调，确认消息发送结果
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual


mybatis:
  mapper-locations: classpath*:mapper/*mapper.xml